### ISSUE TITLE
Segmentation fault in MapHash::collect

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#56]
I haven't had a chance to do any analysis, but there is another seg fault in the new Mapping code. I'll paste the stack trace via gdb in case that's helpful, if it's insufficient I can try to figure out more about what's happening, but all I'm doing is running a patch on a few user objects' mapping values and storing the results to print them in a call_out (my general approach to logging and printing debugging info).

```
#0  0x000055555556b5ca in MapHash::collect (
    this=0x5555558191d0 <vtable for Array+16>, v=0x7ffffff241a0,
    m=0x55555599bbc0, data=0x55555596f438) at array.cpp:294
#1  0x0000555555569000 in Mapping::dehash (this=0x55555599bbc0,
    data=0x55555596f438, clean=true) at array.cpp:1457
#2  0x00005555555693c7 in Mapping::compact (this=0x55555599bbc0,
    data=0x55555596f438) at array.cpp:1533
#3  0x0000555555569431 in Mapping::msize (this=0x55555599bbc0,
    data=0x55555596f438) at array.cpp:1553
#4  0x00005555555e01e7 in kf_map_sizeof (f=0x7fffffffd090, n=1,
    kf=0x555555829198 <kftab+7960>) at std.cpp:929
#5  0x0000555555586fbc in Frame::kfunc (this=0x7fffffffd090, n=202, nargs=1)
    at interpret.cpp:1657
#6  0x0000555555587ff8 in Frame::interpret (this=0x7fffffffd090,
    pc=0x555555a1f3e8 "1\375e\375\070\001\024D\"?\345\001\032\311\061\374e\001\032\313\061\373\245\374%\375\032)\a%") at interpret.cpp:1932
#7  0x0000555555589186 in Frame::funcall (this=0x7fffffffd400,
    obj=0x7fffc9f8bd78, lwobj=0x0, p_ctrli=10, funci=8, nargs=5)
    at interpret.cpp:2254
#8  0x000055555558710d in Frame::vfunc (this=0x7fffffffd400, n=3, nargs=2)
    at interpret.cpp:1677
#9  0x0000555555588352 in Frame::interpret (this=0x7fffffffd400,
    pc=0x555555a1f377 "\n\003\061\377e\375\032)1\376\031") at interpret.cpp:1992
#10 0x0000555555589186 in Frame::funcall (this=0x7fffffffd640,
    obj=0x7fffc9f8bd78, lwobj=0x0, p_ctrli=10, funci=8, nargs=5)
    at interpret.cpp:2254
#11 0x000055555558710d in Frame::vfunc (this=0x7fffffffd640, n=3, nargs=1)
    at interpret.cpp:1677
#12 0x0000555555588352 in Frame::interpret (this=0x7fffffffd640,
    pc=0x555555a1f908 "\n\003\035") at interpret.cpp:1992
#13 0x0000555555589186 in Frame::funcall (this=0x7fffffffdbb0,
    obj=0x7fffc9f8bd78, lwobj=0x0, p_ctrli=10, funci=23, nargs=0)
    at interpret.cpp:2254
#14 0x000055555558988d in Frame::call (this=0x7fffffffdbb0, obj=0x7fffc9f8ed90,
    lwobj=0x0, func=0x5555559bec50 "msg_value", len=9, call_static=0, nargs=1)
    at interpret.cpp:2385
#15 0x00005555555dbdf0 in kf_call_other (f=0x7fffffffdbb0, nargs=3,
    kf=0x555555827af0 <kftab+2160>) at builtin.cpp:2178
#16 0x0000555555586fbc in Frame::kfunc (this=0x7fffffffdbb0, n=54, nargs=3)
    at interpret.cpp:1657
#17 0x0000555555587ff8 in Frame::interpret (this=0x7fffffffdbb0,
    pc=0x555555966280 "\345\370\032)\021\370\032\003\070") at interpret.cpp:1932
#18 0x0000555555589186 in Frame::funcall (this=0x7fffffffe030,
    obj=0x7fffc9f8ba60, lwobj=0x0, p_ctrli=4, funci=13, nargs=9)
    at interpret.cpp:2254
#19 0x000055555558988d in Frame::call (this=0x7fffffffe030, obj=0x7fffc9f8ba60,
    lwobj=0x0, func=0x5555559beb00 "_send_debug", len=11, call_static=0, nargs=2)
    at interpret.cpp:2385
#20 0x00005555555dbdf0 in kf_call_other (f=0x7fffffffe030, nargs=4,
    kf=0x555555827af0 <kftab+2160>) at builtin.cpp:2178
#21 0x0000555555586fbc in Frame::kfunc (this=0x7fffffffe030, n=54, nargs=4)
    at interpret.cpp:1657
#22 0x0000555555587ff8 in Frame::interpret (this=0x7fffffffe030,
    pc=0x555555922f26 "1\371\200\027\032\067\n\001\061\375@\377")
    at interpret.cpp:1932
#23 0x0000555555588493 in Frame::interpret (this=0x7fffffffe030,
    pc=0x555555922f1b "Z\364%\374%") at interpret.cpp:2021
#24 0x0000555555589186 in Frame::funcall (this=0x7fffffffe260,
    obj=0x7fffc9f91730, lwobj=0x0, p_ctrli=0, funci=26, nargs=7)
    at interpret.cpp:2254
#25 0x0000555555588249 in Frame::interpret (this=0x7fffffffe260,
    pc=0x55555592305d "\232:?B\362*\003\001") at interpret.cpp:1976
#26 0x0000555555589186 in Frame::funcall (this=0x555555822e00 <topframe>,
    obj=0x7fffc9f91730, lwobj=0x0, p_ctrli=0, funci=29, nargs=0)
    at interpret.cpp:2254
#27 0x000055555558988d in Frame::call (this=0x555555822e00 <topframe>,
    obj=0x7fffc9f8ba60, lwobj=0x0, func=0x5555559bdc00 "_F_callout", len=10,
    call_static=1, nargs=3) at interpret.cpp:2385
#28 0x0000555555581d63 in CallOut::call (f=0x555555822e00 <topframe>)
    at call_out.cpp:660
#29 0x0000555555595192 in DGD::main (argc=3, argv=0x7fffffffe570) at dgd.cpp:240
#30 0x00005555555eae5d in main (argc=4, argv=0x7fffffffe568) at local.cpp:68
```

**Comment by dworkin** [comment]
It seems like the `this` pointer is corrupt, which could mean that an Array was improperly cast to Mapping. I put some `dynamic_cast`s in the code to catch this eventuality, which won't prevent a crash but will help track it down.

**Comment by nyankers** [comment]
It seems that there is some circumstance in which a Mapping is getting created as an Array instead, although the `type` is correct.

```
1: *f->sp->array = {<ChunkAllocated> = {<No data fields>}, _vptr.Array = 0x55555581a1d0 <vtable for Array+16>, size = 144,
  refCount = 4, tag = 1824, objDestrCount = 2, elts = 0x555555a632d0, primary = 0x555555968208, prev = 0x555555a8e5e8,
  next = 0x555555a8e4a8}
2: (*(void ***)f->sp->array)[0] = (void *) 0x555555566cbc <Array::trim()>
```

```
(gdb) p f->sp->type
$30 = 6 '\006'
```

But it seems to be a rare circumstance, because the vast majority of these calls use the correct class.

After trying to see when and why this array could get generated, I found this stack trace:

```
#0  Array::Array (this=0x5555559e62a0, size=144) at array.cpp:449
#1  0x00005555555669df in Array::alloc (size=144) at array.cpp:499
#2  0x0000555555579631 in Dataspace::import (this=0x555555968408, imp=0x7fffffffe370, val=0x555555a01618, n=1) at data.cpp:3439
#3  0x0000555555579bb2 in Dataspace::xport () at data.cpp:3576
#4  0x0000555555595436 in DGD::endTask () at dgd.cpp:102
#5  0x0000555555581e95 in CallOut::call (f=0x555555823e00 <topframe>) at call_out.cpp:668
#6  0x0000555555595872 in DGD::main (argc=3, argv=0x7fffffffe570) at dgd.cpp:240
#7  0x00005555555eb895 in main (argc=4, argv=0x7fffffffe568) at local.cpp:68
```

Although my initial post was a bit more fuzzy than intended, to clarify, the mapping is stored in a call_out, which is what `Dataspace::xport` seems to be retrieving. Looking at `Dataspace::import`, it seems that it's always creating an Array, even when the value passed in is of a different type (that is in frame 2, `val->type == T_MAPPING`).

**Comment by dworkin** [comment]
Seems like you found it! Should be fixed by the latest commit.

**Comment by nyankers** [comment]
Looks like it's fixed now, thanks!
